/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fdfae3",
        "surface-dim": "#dedbc4",
        "surface-bright": "#fdfae3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8f4dd",
        "surface-container": "#f2efd7",
        "surface-container-high": "#ece9d2",
        "surface-container-highest": "#e6e3cc",
        "on-surface": "#1c1c0e",
        "on-surface-variant": "#504539",
        "inverse-surface": "#323122",
        "inverse-on-surface": "#f5f1da",
        "outline": "#827568",
        "outline-variant": "#d4c4b5",
        "surface-tint": "#7f561f",
        "primary": "#7f561f",
        "on-primary": "#ffffff",
        "primary-container": "#ba894d",
        "on-primary-container": "#402500",
        "inverse-primary": "#f4bc7b",
        "secondary": "#5a6233",
        "on-secondary": "#ffffff",
        "secondary-container": "#dce5a9",
        "on-secondary-container": "#5f6737",
        "tertiary": "#636035",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b2ad7b",
        "on-tertiary-container": "#434119",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffddb8",
        "primary-fixed-dim": "#f4bc7b",
        "on-primary-fixed": "#2b1700",
        "on-primary-fixed-variant": "#643f07",
        "secondary-fixed": "#dfe8ac",
        "secondary-fixed-dim": "#c3cc92",
        "on-secondary-fixed": "#181e00",
        "on-secondary-fixed-variant": "#434a1d",
        "tertiary-fixed": "#eae5ae",
        "tertiary-fixed-dim": "#cdc894",
        "on-tertiary-fixed": "#1e1c00",
        "on-tertiary-fixed-variant": "#4b481f",
        "background": "#fdfae3",
        "on-background": "#1c1c0e",
        "surface-variant": "#e6e3cc",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
