export default {
  appName: "ಏಕೀಕೃತ ಆರೋಗ್ಯ", loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...", save: "ಉಳಿಸು", cancel: "ರದ್ದು ಮಾಡು", back: "ಹಿಂದೆ", submit: "ಸಲ್ಲಿಸು", search: "ಹುಡುಕು", viewAll: "ಎಲ್ಲವನ್ನೂ ನೋಡು", add: "ಸೇರಿಸು", delete: "ಅಳಿಸು", confirm: "ದೃಢೀಕರಿಸು", error: "ದೋಷ", success: "ಯಶಸ್ಸು", logout: "ಲಾಗ್ಔಟ್", profile: "ನನ್ನ ಪ್ರೊಫೈಲ್", overview: "ಅವಲೋಕನ", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
  login: "ಲಾಗಿನ್", register: "ನೋಂದಣಿ", email: "ಇಮೇಲ್ ವಿಳಾಸ", password: "ಪಾಸ್‌ವರ್ಡ್", firstName: "ಮೊದಲ ಹೆಸರು", lastName: "ಕೊನೆಯ ಹೆಸರು", selectRole: "ನಿಮ್ಮ ಪಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ", rememberMe: "ನನ್ನನ್ನು ನೆನಪಿಡು", forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?", agreeTerms: "ಸೇವಾ ನಿಯಮಗಳಿಗೆ ಒಪ್ಪುತ್ತೇನೆ", loginSuccess: "ಲಾಗಿನ್ ಯಶಸ್ವಿ!", registerSuccess: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!", createAccount: "ಖಾತೆ ರಚಿಸಿ", secureAccess: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಸೇವೆಗಳಿಗೆ ಸುರಕ್ಷಿತ ಪ್ರವೇಶ", joinNetwork: "ಏಕೀಕೃತ ಆರೋಗ್ಯ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ", loginBtn: "ಲಾಗಿನ್", registerBtn: "ಖಾತೆ ನೋಂದಾಯಿಸಿ", processing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
  patient: "ರೋಗಿ", doctor: "ವೈದ್ಯರು", staff: "ಸಿಬ್ಬಂದಿ", admin: "ಅಧಿಕಾರಿ",
  myAppointments: "ನನ್ನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", immunizationRecords: "ಲಸಿಕೆ ದಾಖಲೆಗಳು", maternalId: "ಮಾತೃ ID", abhaHealthId: "ABHA ಆರೋಗ್ಯ ID", manageAppointments: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ", patientRecords: "ರೋಗಿ ದಾಖಲೆಗಳು", allAppointments: "ಎಲ್ಲಾ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", manageUsers: "ಬಳಕೆದಾರರನ್ನು ನಿರ್ವಹಿಸಿ", reports: "ವರದಿಗಳು",
  welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ", healthSummary: "ಇಂದಿನ ನಿಮ್ಮ ಆರೋಗ್ಯ ಸಾರಾಂಶ.", upcomingAppointments: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", immunizationsDone: "ಮುಗಿದ ಲಸಿಕೆಗಳು", pendingVaccines: "ಬಾಕಿ ಲಸಿಕೆಗಳು", healthScore: "ಆರೋಗ್ಯ ಸ್ಕೋರ್", good: "ಉತ್ತಮ", bookNewAppointment: "+ ಹೊಸ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ", noUpcomingAppointments: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.", noImmunizationRecords: "ಲಸಿಕೆ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.", todaysAppointments: "ಇಂದಿನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", totalAppointments: "ಒಟ್ಟು ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", completedToday: "ಇಂದು ಮುಗಿದವು", pendingToday: "ಇಂದು ಬಾಕಿ", noAppointmentsToday: "ಇಂದು ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.", noUpcoming: "ಮುಂಬರುವ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.", pendingAppointments: "ಬಾಕಿ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", confirmedToday: "ಇಂದು ದೃಢೀಕರಿಸಲಾಗಿದೆ", vaccinationsToday: "ಇಂದಿನ ಲಸಿಕೆಗಳು", totalRecords: "ಒಟ್ಟು ದಾಖಲೆಗಳು", recentImmunizations: "ಇತ್ತೀಚಿನ ಲಸಿಕೆಗಳು", noPendingAppointments: "ಬಾಕಿ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.", noImmunizationsYet: "ಇನ್ನೂ ಲಸಿಕೆ ದಾಖಲೆಗಳಿಲ್ಲ.", systemOverview: "ಸಿಸ್ಟಮ್ ಅವಲೋಕನ", fullSystemStatus: "ಸಂಪೂರ್ಣ ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ ಇಲ್ಲಿದೆ.", appointmentsThisMonth: "ಈ ತಿಂಗಳ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", vaccinationsThisMonth: "ಈ ತಿಂಗಳ ಲಸಿಕೆಗಳು", uniquePatients: "ವಿಶಿಷ್ಟ ರೋಗಿಗಳು", activeDoctors: "ಸಕ್ರಿಯ ವೈದ್ಯರು", recentAppointments: "ಇತ್ತೀಚಿನ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", noAppointmentsYet: "ಇನ್ನೂ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳಿಲ್ಲ.", quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು", systemHealth: "ಸಿಸ್ಟಮ್ ಆರೋಗ್ಯ", database: "ಡೇಟಾಬೇಸ್", apiServer: "API ಸರ್ವರ್", abhaIntegration: "ABHA ಏಕೀಕರಣ", online: "ಆನ್‌ಲೈನ್", running: "ಚಾಲನೆಯಲ್ಲಿದೆ", sandboxMode: "ಸ್ಯಾಂಡ್‌ಬಾಕ್ಸ್ ಮೋಡ್",
  appointments: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", yourAppointments: "ನಿಮ್ಮ ನಿಗದಿತ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", manageAllAppointments: "ಎಲ್ಲಾ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ", bookAppointment: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಬುಕ್ ಮಾಡಿ", newAppointment: "ಹೊಸ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್", selectDoctor: "ವೈದ್ಯರನ್ನು ಆಯ್ಕೆ ಮಾಡಿ", appointmentType: "ಪ್ರಕಾರ", date: "ದಿನಾಂಕ", time: "ಸಮಯ", notes: "ಟಿಪ್ಪಣಿಗಳು", notesPlaceholder: "ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ...", confirmBooking: "ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ", booking: "ಬುಕ್ ಆಗುತ್ತಿದೆ...", bookingSuccess: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಯಶಸ್ವಿಯಾಗಿ ಬುಕ್ ಆಗಿದೆ!", noAppointmentsFound: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ", clickToBook: "ಪ್ರಾರಂಭಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ", complete: "ಪೂರ್ಣಗೊಳಿಸಿ", done: "ಮುಗಿದಿದೆ", statusPending: "ಬಾಕಿ", statusConfirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ", statusCompleted: "ಮುಗಿದಿದೆ", statusCancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
  immunization: "ಲಸಿಕೆ ದಾಖಲೆಗಳು", yourVaccinations: "ನಿಮ್ಮ ಲಸಿಕೆ ಇತಿಹಾಸ", manageImmunizations: "ರೋಗಿ ಲಸಿಕೆ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ", addRecord: "ದಾಖಲೆ ಸೇರಿಸಿ", addImmunizationRecord: "ಲಸಿಕೆ ದಾಖಲೆ ಸೇರಿಸಿ", patientId: "ರೋಗಿ ID", vaccine: "ಲಸಿಕೆ", dose: "ಡೋಸ್", status: "ಸ್ಥಿತಿ", savingRecord: "ಉಳಿಸಲಾಗುತ್ತಿದೆ...", saveRecord: "ದಾಖಲೆ ಉಳಿಸಿ", recordAdded: "ಲಸಿಕೆ ದಾಖಲೆ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!", noRecordsFound: "ಲಸಿಕೆ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
  maternalTracking: "ಮಾತೃ ಶಿಶು ID ಟ್ರ್ಯಾಕಿಂಗ್", maternalSubtitle: "ಸರ್ಕಾರಿ ಮಾತೃ ID (RCH/MCTS) ಹುಡುಕಿ ಅಥವಾ ನೋಂದಾಯಿಸಿ", enterMaternalId: "ಸರ್ಕಾರಿ ಮಾತೃ ID ನಮೂದಿಸಿ", lookUp: "ಹುಡುಕು", searching: "ಹುಡುಕಲಾಗುತ್ತಿದೆ...", registerNow: "ಈಗ ನೋಂದಾಯಿಸಿ", antenatalVisits: "ಪ್ರಸವಪೂರ್ವ ಭೇಟಿಗಳು", deliveryDetails: "ಹೆರಿಗೆ ವಿವರಗಳು", visitHistory: "ಭೇಟಿ ಇತಿಹಾಸ", noAntenatalVisits: "ಪ್ರಸವಪೂರ್ವ ಭೇಟಿಗಳು ದಾಖಲಾಗಿಲ್ಲ.", addAntenatalVisit: "ಪ್ರಸವಪೂರ್ವ ಭೇಟಿ ಸೇರಿಸಿ", noDeliveryDetails: "ಹೆರಿಗೆ ವಿವರಗಳು ದಾಖಲಾಗಿಲ್ಲ.", addDeliveryDetails: "ಹೆರಿಗೆ ವಿವರಗಳು ಸೇರಿಸಿ", updateDeliveryDetails: "ಹೆರಿಗೆ ವಿವರಗಳು ನವೀಕರಿಸಿ", hospitalId: "ಆಸ್ಪತ್ರೆ ID", optional: "ಐಚ್ಛಿಕ", clinicalNotes: "ಕ್ಲಿನಿಕಲ್ ಟಿಪ್ಪಣಿಗಳು...", addVisit: "ಭೇಟಿ ಸೇರಿಸಿ", saveDeliveryDetails: "ಹೆರಿಗೆ ವಿವರಗಳು ಉಳಿಸಿ", govtMaternalId: "ಸರ್ಕಾರಿ ಮಾತೃ ID", registered: "ನೋಂದಾಯಿಸಲಾಗಿದೆ",
  abhaTitle: "ABHA ಆರೋಗ್ಯ ID", abhaSubtitle: "ಆಧಾರ್ ಬಳಸಿ ನಿಮ್ಮ ABHA ಖಾತೆ ರಚಿಸಿ", abhaInfo: "ABHA ಬಗ್ಗೆ", abhaInfoText: "ABHA ಎಂಬುದು ABDM ಅಡಿಯಲ್ಲಿ ಭಾರತ ಸರ್ಕಾರ ನೀಡುವ 14 ಅಂಕಿಯ ಆರೋಗ್ಯ ID. ಪ್ರಸ್ತುತ", demoMode: "ಡೆಮೋ ಮೋಡ್", abhaInfoText2: "ನಲ್ಲಿ ಚಾಲನೆಯಲ್ಲಿದೆ — OTP ಪರದೆಯ ಮೇಲೆ ತೋರಿಸಲಾಗುತ್ತದೆ.", enterAadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ", verifyOtp: "OTP ಪರಿಶೀಲಿಸಿ", createAbhaId: "ABHA ID ರಚಿಸಿ", done2: "ಮುಗಿದಿದೆ", aadhaarNumber: "ಆಧಾರ್ ಸಂಖ್ಯೆ", aadhaarPlaceholder: "XXXX XXXX XXXX", sendOtp: "OTP ಕಳುಹಿಸಿ", sendingOtp: "OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...", otpSentTo: "ನಿಮ್ಮ ಆಧಾರ್ ಲಿಂಕ್ ಮೊಬೈಲ್‌ಗೆ ಕಳುಹಿಸಿದ OTP ನಮೂದಿಸಿ.", demoModeOtp: "ಡೆಮೋ ಮೋಡ್ — ನಿಮ್ಮ OTP", otp: "OTP", otpPlaceholder: "6 ಅಂಕಿಯ OTP", verifying: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...", preferredAbha: "ಆದ್ಯತೆಯ ABHA ವಿಳಾಸ (ಐಚ್ಛಿಕ)", creating: "ರಚಿಸಲಾಗುತ್ತಿದೆ...", createAbhaBtn: "ABHA ID ರಚಿಸಿ", abhaCreated: "ABHA ID ರಚಿಸಲಾಗಿದೆ!", abhaReady: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಖಾತೆ ಸಿದ್ಧವಾಗಿದೆ", abhaAddress: "ABHA ವಿಳಾಸ", abhaNumber: "ABHA ಸಂಖ್ಯೆ", name: "ಹೆಸರು", gender: "ಲಿಂಗ", yearOfBirth: "ಜನ್ಮ ವರ್ಷ", linkToMaternal: "ಮಾತೃ ದಾಖಲೆಗೆ ಲಿಂಕ್ ಮಾಡಿ", linkToMaternalDesc: "ಈ ABHA ID ಅನ್ನು ಸರ್ಕಾರಿ ಮಾತೃ ದಾಖಲೆಗೆ ಲಿಂಕ್ ಮಾಡಿ.", link: "ಲಿಂಕ್", linking: "ಲಿಂಕ್ ಆಗುತ್ತಿದೆ...", createAnother: "ಮತ್ತೊಂದು ABHA ID ರಚಿಸಿ",
  myProfileTitle: "ನನ್ನ ಪ್ರೊಫೈಲ್", accountInfo: "ನಿಮ್ಮ ಖಾತೆ ಮಾಹಿತಿ", userId: "ಬಳಕೆದಾರ ID", role: "ಪಾತ್ರ",
  ruralHealthCenter: "ಗ್ರಾಮೀಣ ಆರೋಗ್ಯ ಕೇಂದ್ರ", lowBandwidth: "ಕಡಿಮೆ ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್ ಗ್ರಾಮೀಣ ಸಂಪರ್ಕಗಳಿಗೆ ಅನುಕೂಲಿಸಲಾಗಿದೆ",
}
